-- Jalankan di Supabase Dashboard → SQL Editor
-- Schema untuk migrasi dari db.json ke Supabase (PostgreSQL)

-- Users (admin app)
CREATE TABLE IF NOT EXISTS users (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  username TEXT UNIQUE NOT NULL,
  email TEXT UNIQUE,
  auth_user_id UUID UNIQUE,
  password_hash TEXT DEFAULT '',
  role TEXT DEFAULT 'admin',
  created_at TIMESTAMPTZ DEFAULT NOW()
);
ALTER TABLE users ADD COLUMN IF NOT EXISTS email TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS auth_user_id UUID;
ALTER TABLE users ALTER COLUMN password_hash DROP NOT NULL;
ALTER TABLE users ALTER COLUMN password_hash SET DEFAULT '';
DO $$ BEGIN
  ALTER TABLE users ADD CONSTRAINT users_email_unique UNIQUE (email);
EXCEPTION WHEN duplicate_table THEN NULL;
WHEN duplicate_object THEN NULL;
END $$;
DO $$ BEGIN
  ALTER TABLE users ADD CONSTRAINT users_auth_user_id_unique UNIQUE (auth_user_id);
EXCEPTION WHEN duplicate_table THEN NULL;
WHEN duplicate_object THEN NULL;
END $$;

-- Routers (MikroTik)
CREATE TABLE IF NOT EXISTS routers (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name TEXT NOT NULL,
  host TEXT NOT NULL,
  port INT DEFAULT 8728,
  username TEXT NOT NULL,
  password TEXT,
  is_ssl SMALLINT DEFAULT 0,
  integration_mode TEXT DEFAULT 'api',
  is_active SMALLINT DEFAULT 1,
  use_vpn SMALLINT DEFAULT 0,
  vpn_ip TEXT,
  vpn_profile_id TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);
ALTER TABLE routers ADD COLUMN IF NOT EXISTS vpn_profile_id TEXT;

-- Packages (paket langganan)
CREATE TABLE IF NOT EXISTS packages (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name TEXT NOT NULL,
  type TEXT DEFAULT 'pppoe',
  price_monthly NUMERIC(12,2) DEFAULT 0,
  speed_limit TEXT,
  validity_days INT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Customers (pelanggan)
CREATE TABLE IF NOT EXISTS customers (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  router_id BIGINT NOT NULL REFERENCES routers(id),
  package_id BIGINT REFERENCES packages(id),
  name TEXT NOT NULL,
  username TEXT NOT NULL,
  password TEXT,
  type TEXT DEFAULT 'pppoe',
  status TEXT DEFAULT 'active',
  address TEXT,
  phone TEXT,
  email TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(router_id, username)
);

-- Bills (tagihan)
CREATE TABLE IF NOT EXISTS bills (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  customer_id BIGINT NOT NULL REFERENCES customers(id),
  period_start DATE NOT NULL,
  period_end DATE NOT NULL,
  amount NUMERIC(12,2) DEFAULT 0,
  status TEXT DEFAULT 'unpaid',
  due_date DATE,
  paid_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Payments (pembayaran)
CREATE TABLE IF NOT EXISTS payments (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  bill_id BIGINT NOT NULL,
  customer_id BIGINT NOT NULL REFERENCES customers(id),
  amount NUMERIC(12,2) NOT NULL,
  method TEXT DEFAULT 'manual',
  reference TEXT,
  paid_at TIMESTAMPTZ NOT NULL
);

-- Vouchers (voucher hotspot)
CREATE TABLE IF NOT EXISTS vouchers (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  router_id BIGINT NOT NULL REFERENCES routers(id),
  package_id BIGINT REFERENCES packages(id),
  code TEXT NOT NULL,
  duration_minutes INT,
  used SMALLINT DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- App settings (key-value)
CREATE TABLE IF NOT EXISTS app_settings (
  key TEXT PRIMARY KEY,
  value TEXT NOT NULL DEFAULT ''
);

-- Activity logs
CREATE TABLE IF NOT EXISTS activity_logs (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  user_id BIGINT,
  method TEXT,
  path TEXT,
  status INT,
  ip TEXT,
  payload JSONB DEFAULT '{}'::jsonb
);

-- Support tickets
CREATE TABLE IF NOT EXISTS support_tickets (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  subject TEXT NOT NULL,
  customer_id BIGINT REFERENCES customers(id),
  priority TEXT DEFAULT 'normal',
  status TEXT DEFAULT 'open',
  description TEXT,
  closed_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- ODP / POP data
CREATE TABLE IF NOT EXISTS odp_pop (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name TEXT NOT NULL,
  type TEXT DEFAULT 'odp',
  area TEXT,
  address TEXT,
  latitude TEXT,
  longitude TEXT,
  note TEXT,
  status TEXT DEFAULT 'active',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Indeks untuk query sering dipakai
CREATE INDEX IF NOT EXISTS idx_customers_router_username ON customers(router_id, username);
CREATE INDEX IF NOT EXISTS idx_bills_customer_id ON bills(customer_id);
CREATE INDEX IF NOT EXISTS idx_bills_status ON bills(status);
CREATE INDEX IF NOT EXISTS idx_payments_paid_at ON payments(paid_at);
CREATE INDEX IF NOT EXISTS idx_vouchers_router_id ON vouchers(router_id);
CREATE INDEX IF NOT EXISTS idx_activity_logs_at ON activity_logs(at DESC);
CREATE INDEX IF NOT EXISTS idx_support_tickets_status ON support_tickets(status);
CREATE INDEX IF NOT EXISTS idx_support_tickets_customer_id ON support_tickets(customer_id);

-- Optional: tabel FreeRADIUS jika ingin mode RADIUS tetap di Supabase
-- (default prefix "rad": radcheck dan radreply)
CREATE TABLE IF NOT EXISTS radcheck (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  username TEXT NOT NULL,
  attribute TEXT NOT NULL,
  op TEXT DEFAULT ':=',
  value TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS radreply (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  username TEXT NOT NULL,
  attribute TEXT NOT NULL,
  op TEXT DEFAULT ':=',
  value TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_radcheck_username ON radcheck(username);
CREATE INDEX IF NOT EXISTS idx_radreply_username ON radreply(username);
